# tasks file for osp.server: Create server instances and attaches them a network and passes metadata to the instance
- include_tasks: app1.yml
- include_tasks: frontend.yml
- include_tasks: app2.yml
- include_tasks: db.yml
